### ISSUE TITLE
我想问一下后台 的saltstack的版本用的是哪一个

### ISSUE THREAD

**Issue by xiangfei** [voilet/cmdb#41]
我现在链接后台saltstack，现在可以获取主机，不行获取到详细的信息，定位是
[root@salt-master ~]# curl -s -k https://127.0.0.1:8000/login -H "Accept: application/json" -d username=seif -d password=seif -d eauth='pam' 
{"return": [{"perms": [".*", "@wheel", "@runner", "@jobs", "@local_async"], "start": 1506679424.654288, "token": "b26ca92ee86e186e90c125641eb082c754c95ce9", "expire": 1506722624.654289, "user": "seif", "eauth": "pam"}]}[root@salt-master ~]# 
[root@salt-master ~]# 
[root@salt-master ~]# 
[root@salt-master ~]# curl -k https://127.0.0.1:8000/      -H "Accept: application/x-yaml"      -H "X-Auth-Token: b26ca92ee86e186e90c125641eb082c754c95ce9"  -d client='local_async'   -d  expr_form='list'   -d fun='key.list_all'
return: An unexpected error occurred
status: 500

后台报错

[DEBUG   ] Error while processing request for: /
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 434, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 856, in POST
    token=cherrypy.session.get('token')))
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 698, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 66, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 79, in local_async
    return local.run_job(*args, **kwargs)
TypeError: run_job() takes at least 3 arguments (3 given)
[INFO    ] 127.0.0.1 - - [29/Sep/2017:18:04:03] "POST / HTTP/1.1" 500 49 "" "curl/7.29.0"

**Comment by voilet** [comment]
-d expr_form='list' 这个参数去掉，这个方法在查询所有key列表是不可以使用的
